version: '2'
services:
  redis:
     image: redis:2
     command: redis-server --appendonly yes
     ports:
       - "6379:6379"
     volumes:
       - redis-data:/data
volumes:
  redis-data:
    driver: local
networks:
  default: